[package]
name = "doddns-rust"
version = "0.1.0"
authors = ["esell <esell@esheavyindustries.com>"]

[dependencies]
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
clap = "2.29.0"
futures = "0.1"
hyper = "0.11.12"
hyper-tls = "0.1.2"
tokio-core = "0.1"
